### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Arttse** [Itera/learn-service-worker#1]
When `npm start` and opening http://localhost:3000 the server is crashes. Perhaps the issue in  [server.js#L20](https://github.com/Itera/learn-service-worker/blob/8528b574bf76e845f5132d042922e098295c7af2/server.js#L20)

**Comment by relekang** [comment]
That server is not running anymore. It is just a tin wrapper to avoid rate limiting on the github api. I think it should work fine if you point it directly at the github api v3.
